# Generated by Django 4.0.2 on 2022-03-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_organization_user_type_employee_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
