# Generated by Django 4.0.2 on 2022-03-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
