# Generated by Django 4.0.2 on 2022-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_only',
            field=models.BooleanField(default=False),
        ),
    ]
