# Generated by Django 4.0.2 on 2022-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_only',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
